version: '3.8'

services:
  mobiauto-postgres:
    image: postgres:15
    container_name: mobiauto-backend-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mobiauto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mobiauto-backend:
    build: .
    container_name: mobiauto-backend
    restart: always
    depends_on:
      - mobiauto-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://mobiauto-postgres:5432/mobiauto
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
