CREATE TABLE IF NOT EXISTS password_reset_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expiry_date timestamp NOT NULL,
  token varchar(255) NOT NULL,
  usuario_id bigint NOT NULL,
  type varchar(50) NOT NULL,
  CONSTRAINT uq_password_reset_token UNIQUE (usuario_id, type),
  CONSTRAINT fk_password_reset_token_user FOREIGN KEY (usuario_id) REFERENCES usuario (id) ON DELETE CASCADE
);

ALTER TABLE usuario ADD COLUMN first_access BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE usuario SET first_access = FALSE;